### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by albertoconnor** [CassZ/techchallenge#1]
Hi,

Thanks so much for taking the time to do this, we really appreciate it. Can you take a bit more time to take in some feedback and make some changes? Please ask questions if the feedback isn't clear.

1. STATIC_ROOT: Django static system is used to serve Javascript and CSS files to users and shouldn't be used for data you are importing. Doing so expose the raw data file to anyone snooping around your static folders. Update your ingest command to take a parameter of the path on the file system to the file where the import data lives. I think the path would need to be relative to `manage.py`, and remove the use of STATIC_ROOT in management commands.

2. Flake8: Can you install and use flake8 to lint your code, especially for your https://github.com/CassZ/techchallenge/blob/master/djangorest/api/management/commands/ingest_property_csv.py file to clean up formatting and remove unused variables or imports. Don't worry too much about long lines, the length of lines can be adjusted per project.

Thanks,
Albert

**Comment by CassZ** [comment]
Hi Albert,

Thank you very much for your feedback!

I have moved the data file from the static folder to the media folder. I also cleaned up my code with Flake8.

Regards,
Cassandra

**Comment by albertoconnor** [comment]
Thank Cassandra,

I think the MEDIA_ROOT will suffer from similar problems. Can you adjust the command to take a string as a positional argument and then use that string to open the data file?

Thanks,
Albert

**Comment by CassZ** [comment]
Hi Albert,

I am sorry that I did not fix command with positional argument the first time! I just moved the data file to a data folder and updated the command so that it takes a string as path in the data root url. Now the user needs to run **python manage.py ingest_property_csv csv/challenge_data.csv** to handle the csv file.
Link to command file is https://github.com/CassZ/techchallenge/blob/master/djangorest/api/management/commands/ingest_property_csv.py

Thank you very much!

Cassasndra

**Comment by albertoconnor** [comment]
Thanks for making the changes!

Albert
